import ContentCard from '../components/ContentCard.jsx'
import DocumentTitle from '../components/DocumentTitle.jsx'
import PageHero from '../components/PageHero.jsx'
import SectionHeading from '../components/SectionHeading.jsx'
import { images, techTrends } from '../data/content.js'

const techNews = [
  { image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80', alt: 'Placa de circuito e processador', title: 'Novos processadores chegam ao mercado', text: 'Mais desempenho e menor consumo.' },
  { image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80', alt: 'Equipe de startup trabalhando com notebooks', title: 'Startups crescem rapidamente', text: 'Inovação domina o cenário digital.' },
  { image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=80', alt: 'Equipe trabalhando em ambiente tecnológico', title: 'Cloud computing em expansão', text: 'Empresas migram para a nuvem.' },
]

export default function Tecnologia() {
  return <><DocumentTitle title="Tecnologia - Central J1" /><PageHero image={images.homeHero} badge="Tecnologia" title="O futuro está sendo construído agora" description="Inteligência artificial, inovação digital e novas tecnologias estão redefinindo o mundo como conhecemos." primary={{ to: '#destaques', label: 'Explorar' }} secondary={{ to: '#tendencias', label: 'Tendências' }} stats={[{ value: '+120', label: 'Notícias Tech' }, { value: 'IA', label: 'Em alta global' }, { value: '2026', label: 'Era digital' }]} />
  <section id="destaques" className="scroll-mt-24 py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Destaque" title="Principais Notícias Tech" description="As novidades mais relevantes do mundo da tecnologia" /><div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><article className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-lg"><div className="h-72 overflow-hidden sm:h-96"><img src="https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80" alt="Representação visual de inteligência artificial" className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /></div><div className="p-6 sm:p-8"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">IA</span><h3 className="mt-4 text-2xl font-black text-slate-950 sm:text-3xl">Inteligência Artificial revoluciona empresas</h3><p className="mt-3 leading-relaxed text-slate-600">Grandes empresas investem bilhões em automação e inteligência artificial para dominar o mercado global.</p></div></article><div className="grid gap-4">{techNews.map((item) => <article key={item.title} className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-md transition duration-300 hover:-translate-y-1 min-[420px]:flex-row"><img src={item.image} alt={item.alt} className="h-40 w-full rounded-xl object-cover min-[420px]:h-24 min-[420px]:w-28" loading="lazy" /><div><h3 className="font-extrabold text-slate-950">{item.title}</h3><p className="mt-2 text-sm text-slate-600">{item.text}</p></div></article>)}</div></div></div></section>
  <section id="tendencias" className="scroll-mt-24 bg-white py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Tendências" title="O que está em alta" description="As principais áreas que estão dominando o mercado" /><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{techTrends.map((card) => <ContentCard key={card.title} {...card} />)}</div></div></section></>
}
